##-----------------------------------------------------------------------------
## rgen.art
##-----------------------------------------------------------------------------
INCLUDES     ?=
LIBRARIES    ?=
SOURCES      ?= main.cpp\
	lib_xx/emp_xx_call.cpp\
	lib_ast/emp_ast_assert.cpp\
	lib_mem/emp_mem_allocator.cpp\
	lib_mem/emp_mem_util.cpp\
	lib_log/emp_log_logger.cpp\
	lib_cnt/emp_cnt_string.cpp

